spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
      url: jdbc:mysql://localhost:3306/toj
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: toj-user
      password: toj-pass
#?serverTimezone=UTC&characterEncoding=UTF-8