spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/toj?serverTimezone=UTC&characterEncoding=UTF-8
        username: toj-svc
        password: toj-pass
