spring:
    main:
        allow-bean-definition-overriding: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

    jpa:
        database: mysql
        database-platform=org: hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                format_sql: true
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: 'create-drop'

    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?serverTimezone=UTC&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

    jwt:
        access-token-valid-time: ${ACCESS_TOKEN_VALID_TIME}
        refresh-token-valid-time: ${REFRESH_TOKEN_VALID_TIME}
        secret: ${JWT_SECRET}

oauth:
    google:
        base-url: ${GOOGLE_BASE_URL}
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SCERET}
        redirect-url: ${GOOGLE_REDIRECT_URL}


feign:
    client:
        config:
            default:
                loggerLevel: full

cloud:
    aws:
        s3:
            bucket: ${BUCKET_NAME}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false
        credentials:
            instanceProfile: true
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}

mail-sender:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    auth: true
    starttls-enable: true
