version: "3.7"
services:
  toj-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=toj
      - MYSQL_ROOT_PASSWORD=toj-pass
      - MYSQL_USER=toj-user
      - MYSQL_PASSWORD=toj-pass
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql